FROM nginx:alpine

COPY increase-client-max-body-size.conf /etc/nginx/conf.d/00-increase-client-max-body-size.conf
COPY include.conf /etc/nginx/conf.d/include.conf

RUN ["ln", "-sf", "/srv/nginx/conf-gen/default.conf", "/etc/nginx/conf.d/default.conf"]
