version: '2.1'

volumes:
  conf:
  conf-gen:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: nginx

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - conf:/srv/nginx/conf.d:ro
    - conf-gen:/srv/nginx/conf-gen:ro
    - html:/usr/share/nginx/html:ro
    - vhost:/etc/nginx/vhost.d:ro
    - certs:/etc/nginx/certs:ro

  dockergen:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dockergen
    container_name: nginx-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /srv/nginx/conf-gen/default.conf
    volumes:
    - conf-gen:/srv/nginx/conf-gen:rw
    - vhost:/etc/nginx/vhost.d:ro
    - certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
    - html:/usr/share/nginx/html:rw
    - vhost:/etc/nginx/vhost.d:rw
    - certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - NGINX_PROXY_CONTAINER=nginx
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

