FROM nginx

COPY increase-client-max-body-size.conf /etc/nginx/conf.d/00-increase-client-max-body-size.conf
COPY increase-server-names-hash-bucket-size.conf /etc/nginx/conf.d/00-increase-server-names-hash-bucket-size.conf
