version: '2.1'

networks:
  default:
    external:
      name: nginx

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /etc/nginx/conf.d
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /srv/ssl-certificates:/etc/nginx/certs:ro
    - ./increase-client-max-body-size.conf:/etc/nginx/conf.d/00-increase-client-max-body-size.conf

  dockergen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
    - nginx
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
    - nginx
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /srv/ssl-certificates:/etc/nginx/certs:rw
    environment:
    - NGINX_PROXY_CONTAINER=nginx
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

